rubberdok/indok-web

README.md
- Remove open source and awesome badges.
- Add Codecov badge to the README
- Closes #263
=> :memo: docs(#263): add codecov badge

.github/dependabot.yml, .github/workflows/aws.yml
=> ci: fix two typos

.github/workflows/aws.yml, frontend/yarn.lock
- Add Sentry DSN for sending errors to Sentry
=> fix: add sentry dsn

backend/entrypoint.prod.sh
=> fix: api.wsgi -> config.wsgi

.github/workflows/aws.yml, e2e/integration/Dockerfile, e2e/integration/package.json, e2e/integration/yarn.lock
- Download the correct artifact to the expected path
=> fix: artifact download and path

.github/workflows/aws.yml, e2e/integration/Dockerfile
- `${{ matrix.image}}-production` -> `${{ matrix.image }}:production`
=> fix: image re-tagging

frontend/content/organizations/rubberdok.md, frontend/src/components/pages/events/email/ConfirmationsDialog.tsx, frontend/src/components/pages/listings/index/Listings.tsx, frontend/src/components/pages/profile/EditUser.tsx
- replaces deprecated web@indokhs.no email with rubberdok.no emails
- rewords some of the surrounding sentences slightly to flow better
=> fix: change occurrences of web@indokhs.no to rubberdok.no emails

docker-compose.yml
=> Updated docker dependency for backend

frontend/package.json, frontend/src/components/Footer/index.tsx
- Change occurences of hovedstyret link to rubberdok
-
=> prepare site for change of github org link

.github/workflows/aws.yml
- Previous commits were not found, adds `ignore_missing: true` to fallback to the default commit count instead of failing the job.
=> ci(sentry): add `ìgnore_missing: true`

frontend/next.config.js, frontend/src/pages/_app.tsx, frontend/src/pages/_error.tsx
- Add custom `_error.tsx` for capturing and sending errors to Sentry for improved tracing frontend.
=> 📈  tracing(dok-253): capture, send exceptions to sentry frontend

.aws/task-definition.backend.json
=> 🐞  fix: subsrciption -> subscription

frontend/package.json, frontend/yarn.lock
- Remove `react-feather` and `react-icons`
-
=> 🔥 build(react): remove unused dependencies

backend/apps/permissions/resolvers.py, backend/apps/permissions/schema.py, backend/config/schema.py, backend/utils/graphql/schema.py, e2e/integration/cypress/integration/pages/index/feide.spec.ts, frontend/src/components/pages/profile/EditUser.tsx, frontend/src/components/pages/profile/FirstLogin.tsx, frontend/src/components/permissions/PermissionRequired/index.tsx, frontend/src/graphql/cache.ts, frontend/src/graphql/permissions/queries.ts, frontend/src/graphql/users/fragments.ts, frontend/src/graphql/users/mutations.ts, frontend/src/graphql/users/queries.ts, frontend/src/graphql/utils/time/queries.ts, frontend/src/interfaces/users.ts, frontend/src/pages/_app.tsx, frontend/src/pages/authCallback.tsx, frontend/src/pages/profile.tsx
- Cache permissions ⚡ 
- Remove custom caching logic for users, enabling Apollo to handle it automagically 🧙 
- Add dynamic imports for `FirstLogin` and `EditUser` dialogs
- Flashing "Archive"-nav item for all Indøk-users.
=> ⚡  perf: cache permissions, simplify user caching

.github/workflows/aws.yml, frontend/src/components/pages/events/EventDetails.tsx
- serverTime can be undefined when accessing, this prevents that.
-
=> :lady_beetle: fix: ensure `serverTime` is defined before accessing

.gitignore
- Add [Node Version Manager](https://github.com/nvm-sh/nvm#intro) config file (`.nvmrc`) to `.gitignore` to enable contributors to control their local Node version.
=> add .nvmrc to gitignore

.github/workflows/ci.yml
=> fix: don't mask account id

.github/workflows/ci.yml
=> ci: allow concurrent frontend/backend deployments

backend/apps/ecommerce/vipps_utils.py
- Request to gain access to `name` and `phoneNumber` from Vipps user info. This is useful for transaction reports.
- Add more context when exceptions are raised upon calls to Vipps
-
=> Add sentry context on Vipps exceptions and name/phone scope

frontend/package.json, frontend/src/components/pages/profile/ProfileSkeleton.tsx, frontend/src/components/pages/profile/styles.ts, frontend/src/pages/profile/index.tsx
- Avatars are not the correct size on the production site
-
=> 🐞 fix: incorrect avatar size

frontend/src/components/pages/events/AllEvents.tsx, frontend/src/components/pages/profile/ProfileSkeleton.tsx, frontend/src/components/pages/profile/styles.ts, frontend/src/pages/profile/index.tsx
- Filter events based on grade years
- Attempt to fix Avatar sizing on the profile page
-
=> ✨ feat: filter events based on grade years

frontend/next-env.d.ts, frontend/src/components/pages/profile/ProfileSkeleton.tsx, frontend/src/pages/profile/index.tsx, frontend/tsconfig.json
- Add sizes to inline styles for `<Avatar />`, which _should_ resolve #392, verified by running a local production build. Why didn't I do this for the three earlier attempts you ask? Me too. Me too... If this somehow doesn't work, I'm adding `!important`.
- Add `incremental: false` to `tsconfig.json`, as `next build` automatically sets this to `true` if it's not set, yet we should not benefit from setting it to true as we do not have subsequent builds on the same file system, if I understood the benefits correctly. [Docs](https://www.typescriptlang.org/tsconfig#incremental)
- Changes to `next-env.d.ts` are from `next build` - and as the file says, should it should not be manually edited.
- Closes #392
=> 🐞 fix: add inline styling to `<Avatar />` for proper sizing

frontend/src/components/Calendar/CalendarDay.tsx, frontend/src/components/Calendar/index.tsx
=> 🐞 fix: hides dates from previous/next month in view of month

frontend/src/components/pages/events/EventDetails.tsx
=> feat: add markdown renderer to event description

backend/apps/users/tests.py
=> refactor: merge duplicate test query into lambda function

frontend/src/pages/about/index.tsx
- It's important to keep HS satisfied as they're our cash cow. This update adds the names of the current HS leaders to prevent them from feeling left out and voting against our budgets in retaliation.
=> chore: add current hs leaders

frontend/package.json
- The file path is relative to the husky folder, and therefore linting was not run for our project files.
-
=> fix: lint frontend files

frontend/src/components/authentication/LoginRequired/index.tsx, frontend/src/components/navbar/NavbarLinks.tsx, frontend/src/components/pages/events/EventDetails.tsx, frontend/src/components/pages/profile/ProfileCard/variants/PersonalCard.tsx, frontend/src/pages/authCallback.tsx, frontend/src/pages/forms/[...formId].tsx, frontend/src/utils/auth.ts
- Add `<LoginRequired />`-component
- Add helper function for creating Feide logins with custom redirects
- Replace text on `EventDetails.tsx` with an interactive button
**Question**: Should we somehow escape whatever gets sent as state to Feide?
- Closes #402
=> ✨ feat(#402): add login required component with custom redirect

frontend/package.json, frontend/yarn.lock
- Bump Sentry to get the frontend back up and running
Side note, shows the importance of resolving #393 
-
=> 🔥 hotfix: bump sentry

backend/apps/events/types.py
- Resolve user allergies through FK relation instead of through the copied field
- Closes #412
=> feat(#412): resolve user allergies through fk relation

frontend/src/components/pages/events/EventDetails.tsx
- Fix alignment of calendar file download button by ~~wrapping it in a `Box`~~ introducing `Grid`structure
Before <img src="https://user-images.githubusercontent.com/47793383/143293463-295a17d8-3694-444e-8306-5a1f69c33807.png" width=300> After -> <img src="https://user-images.githubusercontent.com/37716832/152397387-11b12a34-1a5d-48a9-ae37-50fe14108451.png" width=300>
- Add `Grid` structure
Before <img src="https://user-images.githubusercontent.com/37716832/152405760-9861ed21-9c36-40ca-9784-4c3d99d1c0ba.png" width=200>  After -><img src="https://user-images.githubusercontent.com/37716832/152405689-8f444053-f706-4220-b080-cb32a4049d3f.png" width=200>
- closes #333
=> Fix calendar file download button alignment issue

backend/apps/ecommerce/mutations.py, backend/apps/events/mutations.py, backend/apps/events/types.py, backend/apps/organizations/fixtures/initial_data.yaml, backend/apps/organizations/types.py, frontend/src/components/navbar/NavbarLinks/links.ts, frontend/src/components/pages/about/Sidebar.tsx, frontend/src/components/pages/about/Template.tsx, frontend/src/components/pages/events/EventCreator.tsx, frontend/src/components/pages/listings/index/ListingItem.tsx, frontend/src/components/pages/listings/organization/ListingForm.tsx, frontend/src/components/pages/profile/ProfileCard/variants/OrganizationCard.tsx, frontend/src/components/pages/profile/ProfileSkeleton.tsx, frontend/src/pages/about/board.tsx, frontend/src/pages/about/index.tsx, frontend/src/pages/about/organization.tsx, frontend/src/pages/orgs/index.tsx, frontend/src/pages/profile/index.tsx, frontend/src/pages/report/index.tsx
- change the use of the word 'organisasjon' on the site to 'forening'
Discussed with HS. 'Forening' is a more natural Norwegian word for the concept of student organizations.
=> chore: rename occurences of 'organisasjon' -> 'forening'

frontend/src/components/pages/profile/ProfileCard/variants/ReportCard.tsx
- change problematic wording of our self-written profile report card
The wording of the report page is known to have issues. While waiting for an updated version of that from the reports committee, this changes the wording written by us on the profile page to be less problematic.
=> fix: report card wording

frontend/src/components/navbar/Navbar.tsx, frontend/src/components/navbar/NavbarLinks/NavbarItem.tsx, frontend/src/components/navbar/NavbarLinks/index.tsx, frontend/src/components/navbar/NavbarLinks/links.ts, frontend/src/components/navbar/NavbarLinks/styles.ts
- (hopefully) fix edge case mis-styling of user button in navbar
- adjust navbar breakpoint to reflect updated navbar content
- refactor navbar styles
- move to using theme.spacing more than hardcoded values
=> fix: navbar user

frontend/src/components/navbar/NavbarLinks/NavbarItem.tsx, frontend/src/components/navbar/NavbarLinks/NavbarUser.tsx, frontend/src/components/navbar/NavbarLinks/styles.ts
- move makeStyles call to fix style cascade (order gets messed up with MaterialUI + Next.js)
- change dropdown to not depend on class name
- also change it to use theme.spacing
=> fix: navbar user button (again...)

frontend/src/graphql/events/mutations.ts
- Ensure match between declared types and variables types for send event email
-
=> fix: send event email variable types

backend/apps/forms/mutations/questions.py, backend/apps/forms/tests.py
- Test creating and updating options
- Test updating answers, failures for blank and missing mandatory questions
-
=> ✅ tests(forms): option mutations, more thorough answer checking

backend/apps/events/mutations.py, frontend/src/components/pages/events/email/EmailFormDialog.tsx
- BCC the user sending event emails
- Partially resolves #453
=> feat: bcc self for event emails

backend/apps/events/mutations.py, backend/apps/events/signals.py, frontend/src/components/pages/events/EventDetails.tsx
- Enforce deadline for events
- Add None checks before comparison
-
=> fix: no signups after deadline, NoneType comparison

frontend/package.json, frontend/yarn.lock
- Remove NPM from `package.json` as it is not used.
- Closes #510
=> build: remove unused npm dependency

backend/templates/user_approved_template.html
- Information about keys are added to the approval email for booking cabins
- closes #515 
- [ x I have tested the changes and verified that they work and do not break anything (to the best of my ability)
=> adds keys info to cabin booking approval email

frontend/src/components/landing/LandingListings.tsx, frontend/src/components/navbar/NavbarLinks/index.tsx
- Resolves issue #523 
- Closes #523
=> Fix(#532): fix no key warning

README.md
- Update `README.md` to reflect changes in installation procedures, and minor improvements.
- #466
=> :memo: docs: update `README.md`

frontend/content/organizations/indoktennis.md
- Richard Rogstad -> Ivar Borge Nore
- Closes #530
=> update indok tennis leader

frontend/content/organizations/hyttestyret.md
- Updated the contact info for the members of Hyttestyret. 
-
=> Update Hyttestyret contact info

backend/schema.json, frontend/codegen.yml, frontend/src/generated/graphql.tsx
- Add the generated `graphql.tsx` file to the commit. 
- #553
=> Feature/update graphql.tsx automatically

.github/pull_request_template.md
- Add the closes keyword as mentioned [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to close the issue automatically when PR is merged. 
- Didn't bother to create an issue..
=> Add closes keyword to close automatically

backend/config/views/csrf.py, frontend/.env.development, frontend/.env.production, frontend/.env.test
- Remove old csrf cookies which prevent users from using our site.
- Closes #
=> fix: remove old csrf cookies

frontend/src/components/authentication/LoginRequired/index.tsx, frontend/src/components/navbar/Navbar.tsx, frontend/src/graphql/users/fragments.ts, frontend/src/graphql/users/mutations.ts, frontend/src/graphql/users/queries.ts, frontend/src/interfaces/users.ts, frontend/src/pages/-/health/index.tsx, frontend/src/pages/authCallback.tsx, frontend/src/pages/profile/index.tsx
- Removing the NavBar during login removes any possibility of running async queries that mess up the user cache.
- This is a pretty crude fix, but it gets the job done.
- Closes #393
=> 🐞 fix: remove navbar during callback

backend/apps/permissions/signals.py
- Add permissions instead of overriding
- Closes #591
=> fix: only add permissions, don't remove for default groups

frontend/src/components/pages/listings/detail/InfoCard.tsx, frontend/src/components/pages/listings/detail/ListingBanner.tsx, frontend/src/components/pages/listings/detail/TitleCard.tsx, frontend/src/generated/graphql.tsx, frontend/src/graphql/listings/fragments.graphql, frontend/src/graphql/listings/queries.graphql, frontend/src/interfaces/listings.ts, frontend/src/interfaces/organizations.ts, frontend/src/pages/listings/[...listingId].tsx
- Add SSR for listings to enable some SEO snacks, such as including the listing title and hero image when sharing.
- Closes #
=> ✨ feat: add ssr and seo for listings

README.md
- add currently missing docker logo (uploaded to `docs/assets`)
- add `title` attribute to readme logos (for hover text)
- format logo `img` tags for readability
=> docs: readme logos

frontend/content/organizations/hyttestyret.md
- Change "Hyttestyret" to "Hytteforeningen". Add info about Mette.
- Closes #
=> 💬 refactor: update about Hytteforening info

frontend/src/pages/cabins/index.tsx
- Edit info paragraphs, update links for transport, change "Hyttestyret" to "Hytteforeningen"
- Closes #
=> 💬 refactor: update cabins info

frontend/src/components/pages/cabins/CabinPrices/index.tsx
- Update price for single bed bookings, and info about rules for booking single beds.
- Closes #
=> Update info cabin (single bed) price

frontend/src/components/pages/cabins/Documents/FAQ.tsx
-Update various answers to match todays info
-Change "Hyttestyret" to "Hytteforeningen"
- Closes #
=> Update cabin FAQ

frontend/src/components/pages/cabins/CabinPrices/index.tsx, frontend/src/components/pages/cabins/Documents/FAQ.tsx, frontend/src/pages/cabins/index.tsx
- Run prettier, this is why having a CI is a great thing 😳 Unfortunately does not work for fork PRs.
- Closes #
=> refactor: run prettier on cabin changes

.github/workflows/ci.yml, backend/decorators/authentication.py, backend/decorators/constants.py, backend/decorators/helpers.py, backend/decorators/permissions.py, backend/decorators/types.py, backend/entrypoints/integration.sh, backend/entrypoints/local.sh, e2e/cypress/integration/pages/index/feide.spec.ts, e2e/package.json, frontend/src/pages/api/health.ts
- Run health checks before running the tests.
- Update some decorator typing
- Fix `wait-for-it` check
- Make E2E required again
- Fixes the last of the flakiness
- Closes #
=> ci(cypress): ensure services are stable prior to tests

backend/apps/ecommerce/tests.py
- Mock `request.*` with appropriate responses to avoid making calls to other services in our API tests
- Closes #613
=> ✅ test: mock vipps api requests

frontend/src/layouts/header/styles.ts, frontend/src/layouts/header/variants/Basic.tsx
- Add animated app bar shadow to appear more smooth
- Reduce the shadow in dark mode
- Remove unused `ElevationScroll` component
- Closes #
=> 🎨 style: animated app bar shadow

backend/apps/cabins/tests.py, backend/utils/testing/cabins_factories.py
- Due to randomness in internal/external participants, the tests were prone to flakiness, i.e. not 100% reproducible, as they could test different parts of the code if external participants > internal participants.
- Closes #
=> ✅ test: fix flaky cabin tests

frontend/cypress.config.ts, frontend/cypress/e2e/landing/feide.cy.ts, frontend/src/components/Auth/LoginRequired/index.tsx, frontend/src/components/landing/LandingPromo.tsx, frontend/src/layouts/components/LoginButton.tsx, frontend/src/layouts/header/variants/Basic.tsx, frontend/src/layouts/navigation/index.tsx, frontend/src/layouts/navigation/variants/Basic/index.tsx, frontend/src/layouts/navigation/variants/Drawer/NavigationLink.tsx, frontend/src/layouts/navigation/variants/Drawer/index.tsx, frontend/src/pages/profile/index.tsx
- Fixes the profile layout
- Note: this cannot be in a `Stack` as there is a weird behavior between `spacing={}` on the stack and `spacing={}` on the grid container, causing the cards to be offset from the center.
- Make login button skeleton fullWidth in drawer
- Wrap navigation in a `Box sx={{ display: { xs: "none", md: "block" } }}` to prevent a flash of desktop navigation on mobile
- Remove key forcing state resets on drawer
- Add `keepMounted` to said drawer for improved performance
- Closes #
=> :art: style: misc changes

frontend/package.json, frontend/src/components/DarkModeToggle/index.tsx, frontend/src/components/DarkModeToggle/variants/Toggle.tsx, frontend/src/components/index.ts, frontend/src/layouts/footer/Footer.tsx, frontend/src/layouts/footer/FooterSimple.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/_document.tsx, frontend/src/pages/profile/index.tsx, frontend/src/theme/index.tsx, frontend/yarn.lock
- Add an initial version of a dark mode toggle to enable toggling between `light | system | dark`, placed bottom left in the footer. Main concern is the discoverability of the toggle.
- Explored other areas such as:
- Navigation drawer, likely a suitable location on mobile, but don't have a nice equivalent for desktop
- App bar, a toggle is too big, so would need a dropdown or something similar
- Top right of the profile page, looked a bit out of place
- Use user's preference when setting the theme
- Set a theme-appropriate `theme-color`
- Add `usehooks-ts` for the `useTernaryDarkMode`-hook to save a user's preference to local storage
- Move `Funnet en feil?` to `Lenker` in the footer
- Style `Hall of Fame` as a link
- Move copyright notice from the bottom to the other part of the footer, …
=> ✨ feat: dark mode toggle

backend/requirements/base.txt
- Bump Django to 3.2.14
- Closes #
=> chore: bump django

frontend/content/organizations/hytteforeningen.md
Added øko/nestleder and drift
- Add board info
- Closes #
=> Update HF board info

README.md
- Add open source snippet to comply with Vercel's sponsorship requirements.
- Closes #
=> chore: add open source snippet to readme

frontend/content/organizations/rubberdok.md, frontend/cypress.config.ts, frontend/src/components/MarkdownForm/components.tsx, frontend/src/pages/about/organizations/[slug].tsx, frontend/src/types/posts.ts, frontend/src/utils/posts.ts
- Make `about us` pages for organizations more phone-friendly
- Closes #
=> 🎨 style: make `about us` more responsive

backend/apps/organizations/mutations.py, frontend/src/components/DarkModeToggle/variants/Toggle.tsx, frontend/src/components/pages/events/EventCreator.tsx, frontend/src/pages/ecommerce/checkout.tsx
- Fix remaining bugs on sonarcloud
- Closes #
=> :bug: fix: sonarcloud bugs

frontend/src/lib/emotion.ts, frontend/src/pages/_document.tsx
=> :recycle: refactor: update nextjs mui setup

frontend/src/components/pages/profile/UserForm/helpers.ts, frontend/src/components/pages/profile/UserForm/index.tsx
- `dayjs().month()` is zero-indexed, so August, which is the breakpoint for new semesters, is 7, not 8.
- Use `lodash/range` instead of custom one
- Fixes #919
=> :bug: fix(#919): graduation year range

.github/workflows/ci.yml, frontend/next.config.js, frontend/package.json, frontend/src/components/Auth/PermissionRequired/index.tsx, frontend/src/components/pages/archive/Documents.tsx, frontend/src/components/pages/archive/FeaturedDocumentsList.tsx, frontend/src/pages/listings/[...listingId].tsx, frontend/src/pages/profile/index.tsx, frontend/yarn.lock
- Avoid redundant queries during SSR
- Remove frontend AWS stuff in CI
- Closes #
=> 🔨  build: vercel accommodations

backend/apps/ecommerce/urls.py, backend/config/urls/local.py, backend/config/urls/production.py, backend/config/urls/test.py
=> fix: preview deployments

frontend/.env.development, frontend/.env.production, frontend/.env.test, frontend/src/lib/apolloClient.ts, frontend/src/utils/config.ts
- The risk level is low, and the current implementation does not address the root issue. Transitioning to a more modern GraphQL server will.
- Closes #
=> chore: remove custom csrf implementation

.github/workflows/api.yml, .github/workflows/ci.yml, .github/workflows/skip-api.yml, .github/workflows/skip-ci.yml
=> ci: add skip workflows

README.md
- add guide for setting up the project without docker
- fix some minor inconsistencies elsewhere in the setup steps
=> docs: add setup guide without docker

README.md
- change database setup to recommend docker for windows too (local postgres setup proved difficult for most of our windows users, and docker works great for this anyways)
- add/fix steps that were missed in initial setup guide
The updated setup has been tested on Windows, and works.
=> fix setup steps in readme

frontend/src/layouts/footer/HallOfFame/constants.ts
=> Add name to hall of fame (Simen)

frontend/src/layouts/footer/HallOfFame/constants.ts
=> add name to hall of fame

frontend/content/organizations/hytteforeningen.md
- One slipped through the cracks
- Closes #
=> fix: update lingering hytteforeningen logo

README.md
- add project structure section to readme
- add development workflow section to readme
- add tech stack section to readme, with links to docs
- update project setup section and fix various other parts of the readme
=> update readme with project structure, dev workflow and tech stack

backend/apps/archive/schema.py, backend/apps/blogs/schema.py, backend/apps/cabins/mutations.py, backend/apps/cabins/schema.py, backend/apps/ecommerce/schema.py, backend/apps/ecommerce/types.py, backend/apps/events/mutations.py, backend/apps/events/schema.py, backend/apps/events/types.py, backend/apps/forms/mutations/questions.py, backend/apps/forms/schema.py, backend/apps/forms/types.py, backend/apps/listings/schema.py, backend/apps/listings/types.py, backend/apps/organizations/schema.py, backend/apps/organizations/types.py, backend/apps/users/schema.py, backend/apps/users/types.py, backend/schema.json, frontend/src/generated/graphql.tsx
- change types of items in `graphene.List` in our api to be `NonNull`
=> change graphql api list items to non-null

README.md
- add readme section on setting up vscode dev environment
- other minor fixes in readme
=> add vscode section to readme, fix other minor stuff

api/docker-compose.yml, api/package-lock.json, api/package.json, api/src/container.ts, api/src/graphql/context.ts, api/src/graphql/generated/types.ts, api/src/index.ts, api/src/repositories/cabins/__tests__/integration/cabins.test.ts, api/src/repositories/cabins/index.ts, api/src/repositories/index.ts, api/src/repositories/permissions/index.ts, api/src/repositories/users/__tests__/integration/users.test.ts, api/src/repositories/users/__tests__/unit/users.test.ts, api/src/repositories/users/index.ts, api/src/services/auth/__tests__/integration/oauth.test.ts, api/src/services/auth/__tests__/unit/oauth.test.ts, api/src/services/auth/index.ts, api/src/services/cabins/__tests__/unit/booking.test.ts, api/src/services/cabins/index.ts, api/src/services/index.ts, api/src/services/mail/index.ts, api/src/services/permissions/index.ts, api/src/services/users/__tests__/unit/user.test.ts, api/src/services/users/index.ts
- Inversify lacks maintainers, tsyringe is maintained by Microsoft.
- Closes #
=> :recycle: refactor: replace inversify with tsyringe

README.md
- update logo author from Skraagen -> mathiasraa, since he changed his name on github
=> fix logo acknowledgement link in readme

frontend/src/layouts/footer/HallOfFame/constants.ts
=> add Torger to hall of fame

frontend/src/components/pages/about/AboutSidebar.tsx, frontend/src/components/pages/about/ItvCard/index.tsx, frontend/src/components/pages/about/ItvCard/types.ts, frontend/src/pages/about/board.tsx, frontend/src/pages/about/itv.tsx
Add about-page for ITV's (Institutt-tillitsvalgte)
* Edit TabPage to include the new tab
* Add itv.tsx to display content
* Create types and components for the new content
- Closes #
=> add about-page for itv

frontend/src/pages/about/board.tsx, frontend/src/pages/about/itv.tsx
- change "Institutt-tillitsvalgte" to "Instituttillitsvalgte" in ITV pages for consistency
=> fix itv typo

frontend/src/layouts/footer/HallOfFame/constants.ts
=> add Thomas to hall of fame

frontend/src/components/pages/organization/OrgMembers.tsx
- Function to sort members by name in organizations
=> add function to sort members  by name

frontend/src/layouts/footer/HallOfFame/constants.ts
=> add fannar to hall of fame

backend/apps/organizations/models.py, backend/apps/organizations/mutations.py
Added custom permission manage_organization to models.py. Changed organizations.change_organization to organizations.manage_organization in the code
=> add custom permission manage_organization

frontend/src/components/pages/organization/OrgMembers.tsx, frontend/src/components/pages/orgs/events/EventInformation/EmailDialog.tsx, frontend/src/pages/orgs/[orgId]/listings/[listingId]/index.tsx
=> chore: remove some console.logs

frontend/src/components/landing/LandingHero/index.tsx, frontend/src/layouts/styles.ts, frontend/src/pages/_app.tsx, frontend/src/pages/cabins/book/index.tsx, frontend/src/pages/orgs/[orgId]/index.tsx, frontend/src/pages/orgs/[orgId]/listings/[listingId]/edit.tsx, frontend/src/pages/orgs/[orgId]/listings/[listingId]/index.tsx, frontend/src/pages/orgs/index.tsx, frontend/src/pages/profile/edit/index.tsx, frontend/src/pages/profile/index.tsx
- Use root style from layout to for consistency
=> refactor: clean up root styles

api/package-lock.json
=> chore: update deps

frontend/src/components/pages/events/EventDetails.tsx, frontend/src/components/pages/listings/detail/TitleCard.tsx, frontend/src/components/pages/listings/organization/OrganizationListings.tsx, frontend/src/components/pages/orgs/events/EventInformation/index.tsx, frontend/src/components/pages/profile/UserForm/index.tsx, frontend/src/pages/ecommerce/fallback.tsx
- Update date formats after adding default localization.
- Available formats: https://day.js.org/docs/en/display/format#list-of-localized-formats
=> :recycle: refactor: update date formats

frontend/content/organizations/rubberdok.md
Change leder pair and amount of members in about us page
=> Update rubberdøk about page

frontend/src/components/pages/Janus/JanusSidebar.tsx, frontend/src/components/pages/Janus/Template.tsx, frontend/src/pages/janus/info.tsx
-Sidebar added to janus project
=> feat: Janus sidebar

frontend/src/components/pages/Janus/JanusSidebar.tsx
=> Add demo into to sidebar

frontend/src/pages/archive.tsx
add januscript as tagtype in frontend archive
-
=> add januscript as tagtype in frontend archive

frontend/src/pages/about/organization.tsx
=> Org map to svg file

frontend/src/pages/janus/info.tsx
=> Janus add info

backend/apps/cabins/mail.py, backend/apps/cabins/tests.py, backend/templates/contract_template.html, backend/templates/user_approved_template.html, backend/templates/user_disapproved_template.html, backend/templates/user_reserve_template.html, frontend/src/components/pages/cabins/Documents/FAQ.tsx
* Update contract html-file
Refactor:
- Update "Hyttestyret" to "Hytteforeningen"
- Update bullet point about cabin rules
* Update html-file cabin booking contract
Refactor:
- Made bullet point identical to tsx-file
* Update backend contract iaw frontend contract
Refactor
- Made backend contract content same as frontend contract refactoring
* Refactor mail sent after booking request
Refactor:
- Update "Hyttestyret" to "Hytteforeningen"
- Typo in mail subject
* Refactor user_reserve_template.html
Refactor:
- "Hyttstyret" -> "Hytteforeningen"
* Refactor user_disapproved_template.html
Refactor:
- "Hyttestyret" -> "Hytteforeningen
* Refactor user_approved_template.html
Refactor:
- "Hyttestyret" -> "Hytteforeningen"
* Update FAQ about cancellation fee
Update bullet point regarding cancellation …
=> Update "Hytteforeningen"-name and contract content (#1254)

backend/apps/events/resolvers.py, backend/apps/events/types.py, backend/schema.json, frontend/src/components/pages/events/CountdownButton.tsx, frontend/src/components/pages/events/EventDetails.tsx, frontend/src/generated/graphql.tsx, frontend/src/graphql/events/fragments.graphql
Reverts rubberdok/indok-web#1231
=> Revert "Resolve from types"

frontend/src/components/pages/events/EventDetails.tsx
- Make extra information box for events bigger to enhance user experience
- Looks bad on smaller screens
=> make extra-info-box bigger

.github/workflows/dependabot.yml
- Accidentally left a filter, remove it.
=> chore: automerge all patch PRs

frontend/src/components/landing/LandingSection.tsx
- For some screen sizes it is possible to scroll horizontally on the landing page due to an overflowing element. This fixes that issue.
=> 🐛 fix: overscrolling on landing page

frontend/src/components/landing/LandingHero/OrganizationsSlider.tsx, frontend/src/components/landing/LandingSection.tsx, frontend/src/layouts/footer/Footer.tsx
- Reduce CLS
- Don't lazy-load LCP
=> chore: a11y and minor perf improvements

frontend/package.json, frontend/src/pages/_app.tsx, frontend/yarn.lock
- Enable [Audiences](https://vercel.com/docs/concepts/analytics/audiences)
=> chore: enable vercel analytics

frontend/src/components/Auth/LoginRequired/index.tsx, frontend/src/layouts/components/ColorModeSwitcher.tsx, frontend/src/layouts/components/LoginButton.tsx, frontend/src/layouts/navigation/variants/Basic/index.tsx
- Add a color switcher with better illustrations of the different modes
- Make the current color theme icon compatible with SSR by changing visibility based on color theme
=> :sparkles: feat: more fun color switcher

frontend/src/components/landing/LandingHero/index.tsx
- Minor placement adjustments to prevent horizontal scroll on the landing page
=> :bug: fix: remove horizontal scroll on landing page

frontend/next.config.js, frontend/src/pages/profile/index.tsx
=> chore: debug slow profile renders

frontend/next.config.js, frontend/src/pages/profile/index.tsx
Reverts rubberdok/indok-web#1585
=> revert: "chore: debug slow profile renders"

frontend/src/components/landing/LandingListings.tsx, frontend/src/components/landing/LandingSection.tsx
=> chore: ensure container consistency on landing page

frontend/package.json, frontend/src/components/pages/cabins/Admin/BookingSemesterPicker/BookingSemesterForm.tsx, frontend/src/components/pages/cabins/Admin/CabinInfoPicker/CabinInfoForm.tsx, frontend/src/components/pages/events/EventForm/EventForm.tsx, frontend/src/components/pages/events/EventForm/schema.ts, frontend/src/components/pages/orgs/events/EventInformation/ConfirmationDialog.tsx, frontend/src/components/pages/orgs/events/EventInformation/EmailDialog.tsx, frontend/src/components/pages/profile/UserForm/helpers.ts, frontend/src/components/pages/profile/UserForm/index.tsx, frontend/src/utils/cabins.ts, frontend/yarn.lock
- Bump Yup to 1.1.1
- Bump @hookform/resolvers to 3.1.0
- Address breaking changes in Yup 1.0
- Move UserForm to react-hook-form and remove formik
=> chore(deps): bump yup to 1.1, @hookform/resolvers to 3.1, remove formik

frontend/src/components/pages/events/AllEvents.tsx, frontend/src/components/pages/events/EventListItem.tsx, frontend/src/components/pages/events/ManageEvents.tsx, frontend/src/generated/graphql.tsx, frontend/src/graphql/events/queries.graphql, frontend/src/pages/events/index.tsx
- Consolidate queries
- Extract conditional logic into components
- Minor component clean up
=> :recycle: refactor: event index page

backend/templates/user_approved_template.html
Added network SSID and password to confirmation email
-
=> Add network info to confirmation email

backend/Dockerfile.prod, frontend/src/components/pages/baksida/ContactInfo.tsx, frontend/src/components/pages/cabins/Documents/FAQ.tsx, frontend/src/components/pages/organization/OrgMembers.tsx, frontend/src/pages/about/organization.tsx, frontend/src/pages/ecommerce/checkout.tsx, frontend/src/pages/ecommerce/fallback.tsx, frontend/src/pages/ecommerce/index.tsx, frontend/src/utils/exports.ts
=> chore: address a bunch of code smells

frontend/src/components/pages/events/EditEvent.tsx
=> fix: update events without registration

frontend/src/components/Markdown/components.tsx
- Add support for links, code, blockquotes, dividers, and update headers
=> ✨ feat: more markdown components

frontend/src/components/pages/events/AllEvents.tsx, frontend/src/components/pages/events/EventListItem.tsx, frontend/src/generated/graphql.tsx, frontend/src/graphql/events/fragments.graphql
- Group events by next week/next two weeks/future
- Show when sign up opens if it's in the future instead of "påmelding tilgjengelig"
=> ✨ feat(events): group by weeks, show sign up open date on overview

frontend/src/components/Auth/LoginRequired/index.tsx
=> fix: circular import

frontend/next.config.js, frontend/package.json, frontend/yarn.lock
- Add `"sideEffects": false` to `package.json` to enable tree shaking for project files, e.g. components
- Add bundle analyzer that can be used by running `ANALYZE=true yarn build`
=> ⚡ perf: enable tree shaking, add bundle analyzer

frontend/cypress/e2e/landing/feide.cy.ts
=> chore(e2e): make feide selection language independent

frontend/content/organizations/hytteforeningen.md
Updated HF new board positions
- Update board info
=> Update hytteforeningen.md (new board info)

backend/apps/users/tests.py, backend/utils/testing/base.py
- `isinstance(obj, class)` instead of `type(obj) == class`
=> chore: lint

frontend/src/pages/forms/[...formId].tsx, frontend/src/pages/orgs/[orgId]/listings/[listingId]/index.tsx
- Forms are not working at all right now. This is a hotfix to make it work properly. Long term, forms should probably be removed as a feature as it has a lot of complexity, and is rarely used.
=> :bug: fix(forms): handle query parameters properly

backend/config/settings/production.py
- Add sentry `baggage` to allowed headers
=> chore: add sentry baggage to allowed headers

frontend/src/layouts/footer/HallOfFame/constants.ts
Add hall of fame for 2023/2024
=> Add prep for hall of fame

frontend/content/organizations/ivi.md
=> Update IVI information

frontend/src/layouts/footer/HallOfFame/constants.ts
- added "Andreas Tauge" to hall of fame
=> Added name to hall of fame

frontend/content/organizations/rubberdok.md
=> add Hannah styre

frontend/src/app/_components/LandingHero/OrganizationsSlider.tsx, frontend/src/pages/about/organization.tsx
- Oppdater medlemsbilder
- Add links to /janus page
- 
-
=> Janus medlemmer and publish

frontend/src/pages/janus/arrangementer.tsx
=> Remove "s"

frontend/package.json, frontend/yarn.lock
=> bum sentry

frontend/src/app/pizza/page.tsx
.../Pizza linked to https://pizzapicker.vercel.app/ easter egg!
-
=> Pizza i boks

frontend/package.json, frontend/src/pages/janus/index.tsx, frontend/yarn.lock
=> Janus e mail

frontend/package.json, frontend/yarn.lock
=> chore: bump sentry

backend/apps/cabins/mail.py, backend/apps/cabins/models.py, frontend/src/components/pages/cabins/booking/Steps/Review.tsx
-fix issue where bookings are not added to DB
=> Fix: Cabin bookings not going to database

frontend/src/layouts/footer/HallOfFame/constants.ts
=> Added Kristian to the Hall of Fame

frontend/src/components/pages/events/EventDetail/SignUp/Actions.tsx
Made the TextField larger to make it more visible
=> Make extra information-TextField larger by adding rows

backend/apps/ecommerce/resolvers.py, frontend/src/pages/janus/shop.tsx
=> Allow people to see products

frontend/src/components/pages/Janus/JanusSidebar.tsx, frontend/src/components/pages/Janus/Shop/PurchaseButton.tsx, frontend/src/components/pages/Janus/Shop/ShopItem.tsx, frontend/src/components/pages/ecommerce/SalesTermsDialog.tsx, frontend/src/pages/janus/[id]/index.tsx
- Write that products have to be picked up at Januskontoret
- Move purchaseButton
- Activate purchaseButton
- Remove size and color options from frontend
=> Publishing changes to shop

frontend/src/components/pages/cabins/BookNow.tsx
- HTS has asked for bed pricing to be removed
=> feat: remove bed pricing

README.md
=> Build: add the old read me

README.md
=> Docs: Reccomend docker for all devs

frontend/src/pages/orgs/[orgId]/listings/[listingId]/index.tsx
=> feat: Remove form creation

frontend/content/organizations/ivi.md
oppdatering IVI tekst og ledere
=> change IVI text

backend/apps/organizations/fixtures/initial_data.yaml, frontend/src/app/_components/LandingHero/Organizations.tsx, frontend/src/app/_components/LandingHero/OrganizationsSlider.tsx, frontend/src/app/_components/LandingHero/index.tsx, frontend/src/app/components/Layout/Footer.tsx, frontend/src/app/layout.tsx, frontend/src/app/page.tsx, frontend/src/components/pages/about/Template.tsx, frontend/src/components/pages/ecommerce/SalesTermsDialog.tsx, frontend/src/layouts/footer/Footer.tsx, frontend/src/layouts/footer/FooterSimple.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/about/board.tsx, frontend/src/pages/about/index.tsx, frontend/src/pages/about/organization.tsx, frontend/src/pages/about/organizations/[slug].tsx, frontend/src/pages/archive.tsx, frontend/src/pages/cabins/index.tsx, frontend/src/pages/events/index.tsx, frontend/src/pages/janus/index.tsx
Change name of student organization and leaders 
-
=> Change organization names

frontend/src/app/components/Layout/AppBar/navigation/constants.tsx, frontend/src/layouts/navigation/constants.tsx
-
Added temporary link for fadderuke
=> Add Arthur site link

frontend/content/organizations/schack.md
oppdatering informasjon og styret
=> updating Janus To Tårn

frontend/content/organizations/ivi.md
=> correct typo

frontend/src/layouts/footer/HallOfFame/constants.ts
- Add hall of fame for current year
=> feat: add hall of fame 24/25

frontend/src/layouts/footer/HallOfFame/constants.ts
- added myself to hall of fame
=> :sparkles: add Tien to Hof

frontend/src/layouts/footer/HallOfFame/constants.ts
=> add Jan to hall of fame

frontend/src/layouts/footer/HallOfFame/constants.ts
Jeg vil bli lagt til i Hall of Fame
=> Add myself to Hall of fame

frontend/src/layouts/footer/HallOfFame/constants.ts
=> Add Erik to hall of fame

frontend/src/app/components/Layout/AppBar/navigation/constants.tsx, frontend/src/layouts/navigation/constants.tsx
=> content: remove bang

frontend/src/components/pages/listings/detail/TitleCard.tsx
Look at the issue. This PR fixes it
-https://github.com/rubberdok/indok-web/issues/2070
=> fix: Misleading tooltip

frontend/content/organizations/eiv.md
=> change contact info EIV

frontend/src/components/pages/cabins/Admin/CabinInfoPicker/index.tsx
I updated the prices for renting cabin.
-
=> Changed prices for cabin

.github/workflows/ci.yml
Old job was deprecated leading to failure
-
=> Updated workflow

frontend/src/app/components/Layout/AppBar/navigation/constants.tsx, frontend/src/layouts/navigation/constants.tsx, frontend/src/pages/listings/index.tsx
Changed title of page "Verv" to "Ledige vervstillinger" to make it more precise.
-
=> Changed title of "Verv"

backend/templates/user_approved_template.html
- Added this sententece to mail:  Dette er en "no-reply"-mail. Ved spørsmål om booking, send mail til booking.indokhyttene@gmail.com
=> Added reminder that  booking mail is no-reply

frontend/src/components/pages/cabins/CabinsDetailsSection.tsx
- The button "Om Janushyttene" led the user to a nonexistent directory, so changed to the right directory.
=> Changed directory of "Om Janushyttene" - button
