- backend/requirements/base.txt
- Add cryptography as an explicit dependency as it is not retrieved using the `PyJWT[crypto]`-syntax.
-
> fix: add cryptography dependency

- backend/entrypoint.sh
- backend/wait-for-it.sh
- Add [wait-for-it.sh](https://github.com/vishnubob/wait-for-it) to `entrypoint.sh` to ensure that the DB is available before the Backend tries to connect. While there is a `depends_on` in the Docker Compose file this does **not** ensure that the DB is ready, only that the DB container is alive. I experienced several times that the DB would start after the Backend and the Backend would never try to reconnect, this will atleast stop that from happening.
> Add wait for it script to ensure db ready before starting backend

- frontend/src/components/pages/events/org/EventsExport.tsx
- frontend/src/components/pages/events/org/OrgEvents.tsx
- frontend/src/components/pages/events/org/OrgEventsTable.tsx
- frontend/src/components/pages/listings/organization/OrganizationListings.tsx
- frontend/src/pages/orgs/[orgId]/index.tsx
- Restructure org admin page file by separating event-related stuff to their own components, to make it more readable
- Fix some uses of Grid
This PR only restructures files, and should not affect functionality.
> refactor event components on org admin page

- .github/dependabot.yml
Keeping our packages up to date is important. However, Dependabot cannot access secrets necessary for pulling images and such due to security concerns. In order to the checks to run, we have to manually re-run the CI jobs. Prior to the CI refactor, this was quite annoying as all workflows had to be re-run, but after the refactor, there's only one workflow to re-run.
I'll be the first to admit that this is not a clean solution by any means, but it's a temporary solution to an important issue.
- Re-add `dependabot.yml` for dependabot updates.
- Scope up permissions to grant access to secrets, which is basically a regression of a security fix implemented by Github.
- De-couple the CI-pipeline completely from secrets, ECR, et cetera - would be great, but I am unsure how to go about this, …
> 🤖 ci(dependabot, dok-201): re-add dependabot config

- frontend/content/organizations/bandok.md
- frontend/content/organizations/bulldok.md
- frontend/content/organizations/business.md
- frontend/content/organizations/eiv.md
- frontend/content/organizations/hyttestyret.md
- frontend/content/organizations/indokrevyen.md
- frontend/content/organizations/indoktennis.md
- frontend/content/organizations/indol.md
- frontend/content/organizations/ivi.md
- frontend/content/organizations/janusfk.md
- frontend/content/organizations/janusfkfk.md
- frontend/content/organizations/janushk.md
- frontend/content/organizations/janustrikk.md
- frontend/content/organizations/mkm.md
- frontend/content/organizations/pandemics.md
- frontend/content/organizations/rubberdok.md
- frontend/content/organizations/schack.md
- frontend/content/organizations/ski-og-lop.md
- frontend/content/organizations/tindok.md
- frontend/content/organizations/typisk.md
- frontend/src/pages/about/organizations/[slug].tsx
#140 included adjusted typings for the organization markdown files, and in the process, something typed as `Array<any>` was changed to `BoardMember[]`, yet the actual type was `Record<string, BoardMember>`, which does not have a `.map` function. Furthermore, the name of the types no longer corresponded to the keys in the markdown files.
- Change all keys in the `.md` files to English.
- Fix the typing of `Frontmatter` 
- Add `mailto:` to the email field
> 🐞 fix(about): restore board info panel

- backend/apps/ecommerce/vipps_utils.py
- backend/requirements/base.txt
- The Sentry SDK is not installed for local builds of the application, causing the import to fail. This PR addresses the issue by setting a filler function if the import fails.
- Removes redundant flake8 from `base.txt`-requirements
> fix: set fallback function if sentry import fails

- frontend/src/components/pages/profile/UserForm/helpers.ts
- frontend/src/components/pages/profile/UserForm/index.tsx
- Always show a users' current graduation year, even if it's not a legal value
- Improve validation
- Users with a graduation year < the current year might be confused when trying to change, as the selector defaults to one of the permitted values. This fixes that issue by showing users their currently selected year, even if it's an illegal value.
> feat: graduation year validation, always show users' graduation year

- backend/apps/ecommerce/__init__.py
- backend/apps/ecommerce/apps.py
- backend/apps/ecommerce/mail.py
- backend/apps/ecommerce/signals.py
- backend/templates/ecommerce/order_confirmation.html
- frontend/src/pages/ecommerce/checkout.tsx
- frontend/src/pages/ecommerce/index.tsx
- Send an order confirmation email when an order is captured. The email currently looks like this:
- closes #401
> Send an order confirmation e-mail upon successfull Vipps payment

- backend/apps/ecommerce/mutations.py
- backend/apps/ecommerce/tests.py
- backend/apps/ecommerce/vipps_utils.py
- Regarding Vipps errors,[ from docs](https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#http-response-codes):
> HTTP responses with errors from the application gateway contain one error JSON object. Error responses produced from the application gateway include `401`, `403`, `422` and `429`.
HTTP responses with errors from the Vipps backend will contain an _array_ of JSON objects.
- This PR checks if an error from vipps is an object or an array of objects before setting context for sentry debugging.
- Additionally, the entire logic for initiating a payment is now encapsulated in an atomic block to ensure that a new order (or a +1 `payment_attempt`) is not saved if we fail to initiate the payment, along with any reserved quantity.
-
> Avoid keyError when setting Sentry context and unroll all changes upon initate payment failure

- backend/apps/ecommerce/vipps_utils.py
- Django shares instantiated classes across processes, and it is therefore possible that users might receive an outdated Vipps access token, see #436 
- Clean up typing in `VippsApi`
- Closes #436
- Fixes INDOKWEB-BACKEND-2A
> fix: never fetch instantiated `access_token`

- frontend/Dockerfile
- frontend/Dockerfile.prod
- frontend/next.config.js
- frontend/package.json
- frontend/yarn.lock
- Bump Node to 16.13.2 (lts)
- Utilize [output file tracing](https://nextjs.org/docs/advanced-features/output-file-tracing) for smaller images
- Add `swcMinify: true` for improved build speeds
- All in all, shaves off about a minute or two from the build times ⚡️
-
> build(node): bump node to 16.13.2, optimize NextJS builds

- frontend/src/pages/orgs/[orgId]/events/[eventId].tsx
- Fix bug causing duplicate hasBoughtTicket columns
- When the event admin page re-renders, an additional column of icons indicating whether the user has bought a ticket is rendered
> Avoid rendering duplicate hasBoughtTicket icons

- backend/apps/events/resolvers.py
- Use the currently saved allergies field on user model when exporting event attendee reports
-
> Use allergies field from user FK in exports

- frontend/yarn.lock
A bug in NextJS 12.0.10 can cause errors that lead to our containers crashing, which is bad. The issue will be resolved by Next 12.0.11
SENTRY3019614692
> ◀️ revert: "build(node): bump next from 12.0.9 to 12.0.10 in /frontend"

- backend/apps/events/resolvers.py
- Add `is_attending: boolean` and `has_paid: boolean` to event exports
- The code here is not very impressive, but it should get the job done in time for Jubileumskom, I'd greatly appreciate it if there is any input on how to improve the exporting.
- Closes #454 #455
> feat: add `is_attending` and `has_paid` to exports

- backend/apps/events/resolvers.py
- Excel does not support TZ aware datetimes, remove it for `order_timestamp`.
- SENTRY5618268
> fix: make tz unaware for xslx export

- backend/config/settings/base.py
- backend/config/settings/production.py
- Add `.indokntnu.no` as JWT cookie domain, so that the cookie is present for both `api.indokntnu.no` and `indokntnu.no`, which enables SSR authentication 💯 
-
> fix: add jwt cookie domain

- backend/api/auth/middleware.py
- We're using a custom JWT middleware, so the cookie's domain is set there.
- Cannot log out due to a mismatch between the cookie domain set on login and when logging out. I.e., `DeleteJSONWebTokenCookie` tries to delete a cookie with domain `indokntnu.no`, but our cookies have domain `api.indokntnu.no`
> fix: set cookie domain

- backend/utils/mail/streams.py
- Avoid setting `template_id` and `global_merge_data` if `template_id` is `None`, as it raises an API error from Postmark due to Anymail attempting to use the Postmark Template API. See [postmark.py#L164](https://github.com/anymail/django-anymail/blob/c7288b9b725db0ff1ad3cb1312bedc523b0cdea7/anymail/backends/postmark.py#L164)
- Closes #593
> fix: allow sending mail without postmark template

- backend/apps/cabins/helpers.py
- backend/apps/cabins/migrations/0002_auto_20200928_1413.py
- backend/apps/cabins/mutations.py
- backend/apps/cabins/tests.py
- backend/apps/cabins/validators.py
- backend/utils/testing/factories/cabins.py
- frontend/src/components/pages/cabins/Hero.tsx
- frontend/src/pages/cabins/index.tsx
- Remove `permission_required` decorators for users to permit bookings without being logged in.
- Remove tests related to requiring permissions for bookings
- Fix minor existing bug in email validation
- Clean up some test cases, add cabin factory
- Side note on why this is necessary: Previously, cabins were created using a migration, however, when running `apps.get_model` in a migration, you get the model at the state at which it had at the time of the migration. For cabins, this included `max_guests = 20`, causing tests with 40 participants to incorrectly pass, as the current default is 18.
- Closes #449
> feat: permit cabin bookings globally

- frontend/next.config.js
- Move `styledComponents`, `reactRemoveProperties` and `removeConsole` to `compiler` as they are now [stable](https://nextjs.org/docs/advanced-features/compiler#supported-features).
- Closes #
> 🔨 build: move stable swc features

- frontend/src/components/pages/cabins/CabinPrices/index.tsx
- Fixed a typo on the cabins front page: interpris -> internpris.
-
> Fix typo on cabins front page

- .github/workflows/ci.yml
- For some reason, playback freezes in Electron, but works fine in Chrome.
- Closes #
> ci: run cypress in chrome to avoid frozen playback

- backend/Dockerfile
- backend/Dockerfile.prod
- backend/apps/archive/fixtures/initial_data.yaml
- backend/apps/archive/google_drive_api.py
- backend/apps/archive/models.py
- backend/apps/archive/types.py
- frontend/Dockerfile
- frontend/Dockerfile.prod
- Move to public base images for Node and Python
- More frequent security updates, no need for authentication. 5 TB of data transfer as an authorized user.
- Use slim Python base image
- Add dependencies for Weasyprint
- Move Google Drive API away from top level to keep it from breaking the app if the secret key is not set.
- Closes #
> 🔨 build: public and smaller base images, minor fixes

- backend/config/urls/base.py
- backend/config/views/health.py
- Add health check that fails if the DB is not migrated, in preparation for moving the migration step out of the entrypoint in order to reduce the time for a new instance to start when scaling up AWS.
- The general idea is:
- Deploy, no worries, container spins up and ELB starts with health checks, which will fail initially. Great, people are still using the stable, previous, release. Simultaneously, a migration task has started and is migrating the DB. As soon as it completes, the health check passes and ELB starts routing requests to the new deployment.
- Closes #
> ✨ feat: migration health check

- frontend/src/components/pages/forms/AnswerForm.tsx
- frontend/src/components/pages/forms/formAdmin/EditForm.tsx
- frontend/src/components/pages/forms/formAdmin/FormResponse.tsx
- frontend/src/components/pages/listings/organization/OrganizationListings.tsx
- sort form questions by id as a temporary solution to keep order consistent
- change confusing/redundant buttons in listing admin page
Long-term, we should implement a proper `order` field on questions, but for now, sorting by ID works, as we do not support changing order of questions. We _sort of_ do this already when answering forms, as we convert questions to an object and then back to an array, which sorts the resulting array by key (ID in this case). This makes this behavior consistent for the admin pages as well.
> refactor(listings): form admin UI

- frontend/next.config.js
- frontend/package.json
- frontend/src/components/Title/variants/BaseTitle.tsx
- frontend/src/components/Title/variants/styles.ts
- frontend/src/components/pages/listings/detail/TitleCard.tsx
- frontend/src/pages/listings/[...listingId].tsx
- Restyle listings index page to bring it more in-line with the rest of the site
- Fix `og:image` with appropriate fallbacks
- Utilize `next/future/image` and enable S3 as asset domain
- Closes #
> :art: style: update listings, fix og:image

- frontend/package.json
- frontend/src/components/Breadcrumbs/index.tsx
- frontend/src/components/DarkModeToggle/index.tsx
- frontend/src/components/DarkModeToggle/variants/Toggle.tsx
- frontend/src/components/NavigationSidebar/NavigationSidebarItem.tsx
- frontend/src/components/landing/LandingHero/OrganizationLink.tsx
- frontend/src/components/landing/LandingHero/Organizations.tsx
- frontend/src/components/pages/about/AboutPageArrow.tsx
- frontend/src/components/pages/archive/SearchBar.tsx
- frontend/src/components/pages/cabins/BookNow.tsx
- frontend/src/components/pages/cabins/ContactCabinBoard/index.tsx
- frontend/src/components/pages/events/EventDetails.tsx
- frontend/src/components/pages/events/filterMenu/FilterMenu.tsx
- frontend/src/layouts/components/LoginButton.tsx
- frontend/src/layouts/navigation/index.tsx
- frontend/src/layouts/navigation/variants/Drawer/index.tsx
- frontend/yarn.lock
- Phosphor icons are nice, but the package does not allow for similar transformation as `@mui/icons-material`, resulting in us pulling in a lot of icons when developing locally, contributing to a severe slow-down of hot reloading in NextJS. This PR replaces the Phosphor icons with similar MUI icons, which also ensures consistency across the site.
- Closes #
> ♻️ refactor: remove `phosphor-react`

- .github/pull_request_template.md
- change the github pull request template to be as simple as possible
The current Pull Request template is quite verbose, and most of the points are often disregarded. In my opinion, this raises the barrier for submitting PRs, when it should be as low as possible. This PR makes the template as simple as possible: a list of changes. If a PR author wishes to include more (like I have, for the Rationale here), they can add it themselves, rather than being forced into the template's format.
> simplify github pull request template

- frontend/src/components/Auth/PermissionRequired/index.tsx
- frontend/src/graphql/permissions/queries.ts
- change `hasPermission` query in `PermissionRequired` component to use generated query instead of `.ts` query
> permissions: change query to use .graphql instead of .ts

- frontend/src/pages/cabins/book/index.tsx
- Show MobileStepper on stage 3, not sure why this was explicitly hidden before?
- (Might have been a mistake seeing as its not supposed to show on stage 4)
- Also changed "send søknad" to "send". Its obvious what you are sending, and also it fits and looks better when viewed on mobile 😄
> show button for sending booking request on mobile

- backend/apps/events/resolvers.py
- frontend/src/components/pages/orgs/events/Table.tsx
- frontend/src/generated/graphql.tsx
- frontend/src/graphql/events/fragments.graphql
- Add extra information to the list of exported fields in the export resolver
- Add a column for extra information in the events overview on the organization page
- Add a `noWrap` to the name column in the same table
> 🐛 fix: include extra information for sign ups in exports and overview

- .github/workflows/dependabot.yml
The _vast_ majority of our dependencies follow [Semantic Versioning](https://semver.org). While I recommend reading the documentation, it basically boils down to three different kinds of updates: <MAJOR>.<MINOR>.<PATCH>. Where PATCH is bug fixing, no breaking changes. As these are the most frequent kinds of updates, it can be quite tedious and redundant to manually approve and merge such PRs from Dependabot. Therefore, this PR adds auto-approval to all dependabot PRs, and enables automerge for PATCH updates.
Retrieved from [Automating Dependabot with GitHub Actions](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#approve-a-pull-request)
- Add workflow to automatically approve all Dependabot PRs
- Add job to enable …
> 👷 ci(dependabot): approve and enable auto-merge for dependabot patch PR

- frontend/src/pages/about/organization.tsx
- frontend/src/utils/posts.ts
- Minor clean up, extract card into separate component
- Use next/image instead of default card media for improved performance
> :zap: perf: use next image for about/organization

- frontend/sentry.edge.config.ts
- frontend/src/pages/_error.tsx
- [with-sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry)
> chore: add sentry edge config, update to latest with-sentry example

- frontend/src/components/pages/events/EventListItem.tsx
- Use logical or `||` instead of nullish coalescing operator `??` when determining fallback for no short description. Also catches `""`, i.e. the empty string
> fix(events): fallback with `""` short description

- README.md
- frontend/package.json
- frontend/yarn.lock
- 18 is LTS, and is what we're actually using.
- Update installation instructions in the readme to clarify that we should be using LTS, not 16.
> chore(deps): bump @types/node to 18

- frontend/src/app/components/PermissionRequired/index.tsx
- Return `null` if permission is falsy, otherwise render children.
> :bug: fix: don't return children if the permission is falsy

- frontend/src/components/pages/events/AllEvents.tsx
- Right now, we filter next week's events with an inclusive between, so we display all events that between 1 and 2 weeks in the future. This PR fixes that by not including events that are two weeks ahead using only a left-inclusive between.
- Events that are > 1 week in the future are moved to "Fremtidige Arrangementer"
> :bug: fix: only show next week's events

- frontend/src/pages/cabins/book/index.tsx
- Replace `useEffect` with variables that are derived from state instead of states that are synced with `useEffect`. This change fixes the infinite render cycle that prevents users from proceeding with bookings.
Cabins are overdue for an overhaul, but the scope of this PR is intentionally kept small and just addresses the immediate issue.
> :bug: fix: infinite re-renders when booking cabins

- frontend/.eslintrc.cjs
- frontend/src/pages/about/organization.tsx
- frontend/src/utils/posts.ts
- Make stylistic errors no longer blocking
- Remove rule that permits the use of `any`
> ♻️ refactor: make stylistic eslint errors `warn` instead of `error`

- frontend/src/components/pages/listings/detail/TitleCard.tsx
- If someone found an old listing, for example by googleling "indøk infi" they might get an old listing. It was hard to tell that it was old and so some people applied to old listings.
###Fix
- Disabled apply button if deadline had passe and added a tooltip to nudge people to take a look at deadline
> fix: old listings

- frontend/src/components/pages/listings/index/ListingItem.tsx
- set image size to stop image from overflowing its container size
Before:
After:
> fix: dont let image overflow parent
